"use client";

import Link from "next/link";
import { useAuth } from "@/lib/hooks/useAuth";

export default function PrivacyPage() {
  const { user, loading } = useAuth();

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="flex justify-between items-center h-16 px-margin-desktop bg-surface border-b border-outline-variant">
        <Link href="/" className="font-sans text-[24px] leading-8 font-semibold font-bold text-primary">
          Kinetic Motor Systems
        </Link>
        {!loading && (
          <Link
            href={user ? "/dashboard" : "/login"}
            className="h-10 bg-primary text-on-primary font-mono text-[12px] leading-4 tracking-[0.05em] font-bold transition-all hover:opacity-90 active:scale-95 flex items-center justify-center gap-2 px-6"
          >
            {user ? "Dashboard" : "Login"}
          </Link>
        )}
      </header>

      <main className="flex-1 p-margin-desktop max-w-3xl mx-auto w-full flex flex-col gap-[24px]">
        <div>
          <h2 className="font-sans text-[24px] leading-8 font-semibold text-primary">
            Privacy Policy
          </h2>
          <p className="font-sans text-[16px] leading-6 text-on-surface-variant mt-1">
            Last Updated: June 2026
          </p>
        </div>

        <section className="bg-surface border border-outline-variant rounded-lg p-6 space-y-4 font-sans text-[14px] leading-5 text-on-surface-variant">
          <p>
            This Privacy Policy describes how the <strong>IoT Smart Metering on Stepper Motor
            Testbed</strong> (&ldquo;Project&rdquo;, &ldquo;Platform&rdquo;,
            &ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) collects, uses, processes,
            stores, and protects information generated through the operation of the smart metering
            system and associated web applications.
          </p>
          <p>
            This Project is developed for <strong>research, educational, and demonstration
            purposes</strong> using IoT edge devices including ESP32, STM32, Raspberry Pi,
            Microsoft Azure cloud services, and related analytics and monitoring platforms.
          </p>
          <p>By accessing or using the Platform, you agree to this Privacy Policy.</p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            1. Information We Collect
          </h3>

          <h4 className="font-sans text-[14px] leading-5 font-semibold text-on-surface">
            1.1 Device and Telemetry Data
          </h4>
          <p>
            The Project may collect operational telemetry from connected IoT devices, including
            voltage measurements, current measurements, power consumption data, power factor,
            frequency measurements, harmonic distortion (THD), load signatures for Non-Intrusive
            Load Monitoring (NILM), device uptime and diagnostic logs, edge inference outputs,
            and protection and fault detection events. Telemetry is primarily generated by embedded
            microcontrollers, sensors, and edge computing devices connected to the Platform.
          </p>

          <h4 className="font-sans text-[14px] leading-5 font-semibold text-on-surface mt-4">
            1.2 Technical, Device, Network, and Analytics Information
          </h4>
          <p>
            We may automatically collect technical information when users access the Platform,
            including IP address, approximate geographic location derived from IP address, browser
            type and version, operating system information, device type and hardware characteristics,
            screen resolution and device capabilities, referring website or traffic source, pages
            visited and navigation behavior, session activity and timestamps, network information
            and connection metadata, Azure IoT Hub connection metadata, website performance metrics,
            and error reports and diagnostic logs.
          </p>
          <p>
            This information is collected for operational monitoring, analytics, diagnostics,
            security, performance optimization, troubleshooting, and platform improvement.
          </p>

          <h4 className="font-sans text-[14px] leading-5 font-semibold text-on-surface mt-4">
            1.3 User-Provided Information
          </h4>
          <p>
            The Platform may include dashboard login functionality and user management features.
            Where applicable, we may collect name, email address, authentication provider
            information, and account-related preferences. Providing such information is optional
            unless required for authentication, authorization, or access control.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            2. How We Use Information
          </h3>
          <p>
            Collected information may be used to operate the smart metering system, process and
            visualize telemetry data, perform Non-Intrusive Load Monitoring (NILM), analyze
            electrical consumption and power quality behavior, monitor system health and device
            status, enable protection and fault detection mechanisms, conduct research and
            development activities, improve system performance and reliability, secure the Platform
            against misuse or unauthorized access, generate aggregated analytics and usage insights,
            and support academic evaluation, project reporting, and documentation.
          </p>
          <p>
            We do <strong>not</strong> sell, rent, or commercially trade personal information.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            3. Edge Processing and Cloud Architecture
          </h3>
          <p>
            This Project follows an <strong>edge-intelligent architecture</strong>. NILM inference,
            protection logic, and certain processing functions are executed locally on embedded
            devices. Only selected telemetry, summaries, analytics, or operational data may be
            transmitted to cloud infrastructure. Critical actuation and protection decisions are
            designed to operate locally without requiring cloud connectivity.
          </p>
          <p>
            Cloud services may include Microsoft Azure services such as Azure IoT Hub, Azure
            Storage, Azure App Services, Azure Monitor, and Azure Analytics Services. Data processed
            through these services may also be subject to the privacy and security practices of the
            respective providers.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            4. Website Analytics and Visitor Monitoring
          </h3>
          <p>
            To understand how visitors interact with the Platform, we use analytics and monitoring
            services, including <strong>Vercel Analytics</strong> and related infrastructure
            monitoring tools. These services may collect information such as visitor country, region,
            and approximate location; device type and operating system; browser information; traffic
            sources and referral information; page views and navigation patterns; session activity;
            website performance metrics; and reliability and error monitoring information.
          </p>
          <p>
            Analytics information helps us measure website traffic, understand platform usage,
            improve user experience, monitor system performance, detect security issues and abuse,
            and identify technical problems. Analytics data is generally processed in aggregated form
            and is used solely for operational, analytical, security, and research purposes.
          </p>
          <p>
            We do not use analytics data for behavioral advertising or targeted marketing.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            5. Data Storage and Security
          </h3>
          <p>
            We implement reasonable administrative, technical, and organizational safeguards to
            protect information, including TLS-encrypted communications, Azure IoT Hub security
            controls, device authentication mechanisms, restricted API access, cloud access controls,
            firewall protections, local edge processing to minimize unnecessary cloud exposure, and
            monitoring and logging systems.
          </p>
          <p>
            Despite these safeguards, no electronic system can guarantee absolute security.
            Users acknowledge that internet-based communication and cloud services involve inherent
            risks, and prototype or research systems may contain limitations. The Platform should not
            be relied upon for highly sensitive, safety-critical, or mission-critical applications.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            6. Data Sharing
          </h3>
          <p>
            Information may be shared only when necessary: with cloud and infrastructure providers
            for system operation, with analytics providers for traffic measurement and performance
            monitoring, with research supervisors, evaluators, or academic reviewers, to comply with
            legal obligations, to investigate security incidents, or to protect the rights, safety,
            and integrity of the Platform. We do not share personal information for advertising,
            marketing, or commercial resale purposes.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            7. Third-Party Services
          </h3>
          <p>
            The Platform may integrate third-party services including Microsoft Azure, Vercel,
            ThingSpeak, Edge Impulse, authentication providers, and analytics and monitoring
            platforms. These services operate under their own privacy policies and terms of service.
            We are not responsible for the independent privacy practices of third-party providers.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            8. Data Retention
          </h3>
          <p>
            Telemetry, logs, analytics information, and operational records may be retained for
            research purposes, analytics and reporting, system diagnostics, academic documentation,
            performance evaluation, and security investigations. As this is a research and
            demonstration platform, data may be periodically deleted or reset, development
            environments may be reformatted, retention periods may vary, and long-term storage is
            not guaranteed.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            9. Research and Educational Disclaimer
          </h3>
          <div className="flex items-start gap-3 p-4 bg-error/5 border border-error/20 rounded-lg">
            <span className="material-symbols-outlined text-error text-[24px] mt-0.5 flex-shrink-0">
              warning
            </span>
            <p className="text-error">
              <strong>Safety and accuracy are not guaranteed.</strong> This Project is intended
              solely for academic research, engineering experimentation, prototype validation, and
              educational demonstration. The Platform is <strong>not certified for commercial
              utility metering</strong>, industrial deployment, regulatory compliance, or
              production-critical operation. System behavior, measurements, availability, and
              functionality may change without notice. Data may be modified, deleted, or
              unavailable during testing and development activities.
            </p>
          </div>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            10. Your Rights
          </h3>
          <p>
            Subject to applicable laws, including India&rsquo;s <strong>Digital Personal Data
            Protection Act, 2023 (DPDP Act)</strong> and other applicable regulations, users may
            have rights regarding their personal information, including access to personal data,
            correction of inaccurate information, deletion of personal data, withdrawal of consent
            where applicable, and requesting information about data processing activities. Requests
            may be submitted using the contact information provided below. We will make reasonable
            efforts to respond within an appropriate timeframe consistent with applicable law.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            11. International Data Transfers
          </h3>
          <p>
            Cloud providers, analytics platforms, and infrastructure services may process or store
            information outside India. By using the Platform, you acknowledge and consent to such
            transfers where reasonably necessary for system operation, analytics, research,
            development, and security purposes.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            12. Changes to This Privacy Policy
          </h3>
          <p>
            We may update this Privacy Policy from time to time to reflect architectural changes,
            new analytics integrations, infrastructure upgrades, security improvements, research
            requirements, or regulatory or legal developments. The updated version will be posted
            on this page with a revised &ldquo;Last Updated&rdquo; date. Continued use of the
            Platform after changes become effective constitutes acceptance of the revised Privacy
            Policy.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            13. Contact
          </h3>
          <p>
            <strong>Project Owner:</strong> IoT Embedded Lab, Dept. of Electronics &amp;
            Instrumentation Engineering<br />
            R.V. College of Engineering, Bengaluru &mdash; 560059<br />
            India<br />
            <a href="mailto:principal@rvce.edu.in" className="text-primary hover:underline">
              principal@rvce.edu.in
            </a>
          </p>
          <p>
            For privacy-related inquiries, data requests, or questions regarding this Privacy
            Policy, please contact us using the information above.
          </p>
        </section>
      </main>
    </div>
  );
}
