"use client";

import Link from "next/link";
import { useAuth } from "@/lib/hooks/useAuth";

export default function PrivacyPage() {
  const { user, loading } = useAuth();

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="flex justify-between items-center h-16 px-margin-desktop bg-surface border-b border-outline-variant">
        <Link href="/" className="font-sans text-[24px] leading-8 font-semibold font-bold text-primary">
          Kinetic Motor Systems
        </Link>
        {!loading && (
          <Link
            href={user ? "/dashboard" : "/login"}
            className="h-10 bg-primary text-on-primary font-mono text-[12px] leading-4 tracking-[0.05em] font-bold transition-all hover:opacity-90 active:scale-95 flex items-center justify-center gap-2 px-6"
          >
            {user ? "Dashboard" : "Login"}
          </Link>
        )}
      </header>

      <main className="flex-1 p-margin-desktop max-w-3xl mx-auto w-full flex flex-col gap-[24px]">
        <div>
          <h2 className="font-sans text-[24px] leading-8 font-semibold text-primary">
            Privacy Policy
          </h2>
          <p className="font-sans text-[16px] leading-6 text-on-surface-variant mt-1">
            IoT Smart Metering on Stepper Motor Testbed
          </p>
        </div>

        <section className="bg-surface border border-outline-variant rounded-lg p-6 space-y-4 font-sans text-[14px] leading-5 text-on-surface-variant">
          <p>
            This Privacy Policy describes how the <strong>IoT Smart Metering on Stepper Motor
            Testbed</strong> (&ldquo;Project&rdquo;, &ldquo;Platform&rdquo;, &ldquo;we&rdquo;)
            collects, processes, stores, and protects information generated through the
            operation of the smart metering system.
          </p>
          <p>
            This Project is developed for <strong>research, educational, and demonstration
            purposes</strong> using IoT edge devices including ESP32, STM32, Raspberry Pi,
            and Microsoft Azure cloud services.
          </p>
          <p>By accessing or using the Platform, you agree to this Privacy Policy.</p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            1. Information We Collect
          </h3>

          <h4 className="font-sans text-[14px] leading-5 font-semibold text-on-surface">
            1.1 Device and Telemetry Data
          </h4>
          <p>
            The Project may collect operational telemetry from connected IoT devices,
            including voltage, current, power consumption, power factor, frequency,
            harmonic distortion (THD), load signatures for NILM processing, device
            uptime and diagnostic logs, and edge inference outputs. Telemetry is
            primarily generated by embedded microcontrollers and edge devices.
          </p>

          <h4 className="font-sans text-[14px] leading-5 font-semibold text-on-surface mt-4">
            1.2 Technical and Network Information
          </h4>
          <p>
            We may automatically collect IP address, device identifiers, Wi-Fi network
            information, browser and operating system information, Azure IoT Hub
            connection metadata, and usage logs and timestamps for operational
            monitoring, diagnostics, and security.
          </p>

          <h4 className="font-sans text-[14px] leading-5 font-semibold text-on-surface mt-4">
            1.3 User-Provided Information
          </h4>
          <p>
            The Platform includes dashboard login functionality and may collect name,
            email address, and authentication provider information. Providing such
            information is optional unless required for access control.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            2. How We Use Information
          </h3>
          <p>
            Collected information is used to operate the smart metering system, perform
            Non-Intrusive Load Monitoring (NILM), analyze electrical and power quality
            behavior, monitor system health, enable real-time protection mechanisms,
            improve research and development, visualize telemetry on dashboards, and
            maintain system security.
          </p>
          <p>
            We do <strong>not</strong> sell or commercially trade personal data.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            3. Edge Processing and Cloud Architecture
          </h3>
          <p>
            This Project follows an <strong>edge-intelligent architecture</strong>.
            NILM inference and protection logic are executed locally on embedded devices.
            Only compressed or semantic telemetry is transmitted to the cloud. Critical
            actuation decisions are performed locally without cloud dependency.
          </p>
          <p>
            Cloud services are provided through Microsoft Azure (IoT Hub, Storage, App
            Services, Monitor). Data processed through Azure services is subject to
            Microsoft&rsquo;s infrastructure and privacy practices.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            4. Data Storage and Security
          </h3>
          <p>
            We implement reasonable safeguards including TLS-encrypted communication
            with Azure IoT Hub, device authentication credentials, restricted API
            access, firewall and cloud access controls, and local edge processing to
            minimize cloud exposure.
          </p>
          <p>
            However, no electronic system can guarantee absolute security. Network
            transmission carries inherent risks. Prototype and research systems may
            contain limitations. Users should avoid using the Platform for highly
            sensitive or mission-critical applications.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            5. Data Sharing
          </h3>
          <p>
            Information may be shared only with cloud infrastructure providers strictly
            for system operation, with research supervisors or academic evaluators where
            required, to comply with legal obligations, or to protect the safety and
            integrity of the Platform. We do not share personal data for advertising or
            marketing purposes.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            6. Data Retention
          </h3>
          <p>
            Telemetry and operational logs may be retained for research, analytics,
            debugging, academic documentation, and project reporting. As this is a
            research/demo platform, data may be reset or deleted periodically, devices
            may be reformatted during development, and long-term retention is not
            guaranteed.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            7. Third-Party Services
          </h3>
          <p>
            The Project may integrate third-party platforms including Microsoft Azure,
            ThingSpeak, and Edge Impulse. These services operate under their own privacy
            policies. We are not responsible for independent third-party privacy
            practices.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            8. Research and Educational Disclaimer
          </h3>
          <div className="flex items-start gap-3 p-4 bg-error/5 border border-error/20 rounded-lg">
            <span className="material-symbols-outlined text-error text-[24px] mt-0.5 flex-shrink-0">
              warning
            </span>
            <p className="text-error">
              <strong>Safety is not guaranteed.</strong> This Project is intended for
              academic research, engineering experimentation, prototype validation, and
              educational demonstration. The Platform is <strong>not certified for
              commercial utility metering</strong> or production-grade industrial
              deployment. Accuracy may vary, features may change, services may be
              interrupted, and data may be deleted during testing cycles.
            </p>
          </div>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            9. Your Rights
          </h3>
          <p>
            Subject to applicable laws including India&rsquo;s Digital Personal Data
            Protection Act, 2023, users may have the right to request access to stored
            personal data, correction of inaccurate information, deletion of data, and
            withdrawal of consent for processing. Requests may be submitted to the
            contact below and we will respond within a reasonable timeframe.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            10. International Data Transfers
          </h3>
          <p>
            Cloud infrastructure providers may process or store information outside
            India. By using the Platform, you consent to such transfers where necessary
            for system operation and research activities.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            11. Changes to This Privacy Policy
          </h3>
          <p>
            We may update this Privacy Policy to reflect architectural changes, Azure
            service integrations, security improvements, or regulatory requirements.
            Continued use after updates constitutes acceptance of the revised policy.
          </p>

          <h3 className="font-sans text-[16px] leading-6 font-semibold text-on-surface mt-6">
            12. Contact
          </h3>
          <p>
            <strong>Project Owner:</strong> IoT Embedded Lab, Dept. of Electronics &amp;
            Instrumentation Engineering<br />
            R.V. College of Engineering, Bengaluru — 560 059<br />
            <a href="mailto:principal@rvce.edu.in" className="text-primary hover:underline">
              principal@rvce.edu.in
            </a>
          </p>
        </section>
      </main>
    </div>
  );
}
